apiVersion: v1
kind: Service
metadata:
  labels:
    app: kong
  name: kong
  namespace: thp-kong
spec:
  type: ClusterIP
  ports:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: https
    port: 8443
    targetPort: 8443
    protocol: TCP
  - name: http-admin
    port: 8001
    targetPort: 8001
    protocol: TCP 
  - name: https-admin
    port: 8444
    targetPort: 8444
    protocol: TCP 
  selector:
      app: kong
